### ISSUE TITLE
Delete bootstrap.json if it exists

### ISSUE THREAD

**Issue by erikng** [erikng/installapplications#25]
Prior to downloading the bootstrap.json file, we should check if one already exists and delete it.

This is for cases where installapplications has failed (say network timeout) and then tries to restart later, but the admin has updated the packages/scripts. 

When this happens, the hash validation fails, causing installapplications to repeatedly fail.

**Comment by mrkidd** [comment]
Please make this optional. We need to bundle the bootstrap.json in the package as our on-boarding is on a restricted network and we don't have anyplace to download from until we can switch to a corporate network. Thanks!

**Comment by erikng** [comment]
Addressed here: https://github.com/erikng/installapplications/commit/1c313067de7afda2c7553e22492a702344fae42c

@mrkidd I have made this optional, however by default it's going to delete and re-check. This commit has documentation on how you can prevent this.

**Comment by mrkidd** [comment]
WFM, thanks!
