### ISSUE TITLE
Error output not handled correctly

### ISSUE THREAD

**Issue by MichalMMac** [erikng/installapplications#47]
I managed to crash installapplications.py on this line:
https://github.com/erikng/installapplications/blob/bf4c5c39b25e157522ee227b2ecdb23137b9096a/payload/Library/Application%20Support/installapplications/installapplications.py#L227

```
Traceback (most recent call last):
  File "/Library/Application Support/installapplications/installapplications.py", line 730, in <module>
    main()
  File "/Library/Application Support/installapplications/installapplications.py", line 688, in main
    runrootscript(path, donotwait)
  File "/Library/Application Support/installapplications/installapplications.py", line 227, in runrootscript
    (pathname, err))
  File "/Library/Application Support/installapplications/installapplications.py", line 57, in iaslog
    NSLog('[InstallApplications] ' + text)
ValueError: Too few arguments for format string [cur:1/len:1]

```

`pathname` contained string.
 `err` contained curl status output.

**Comment by erikng** [comment]
Yes, you must be using curl within your scripts. Please pass `-s` your curl command. I do not plan on addressing this issue. If you are curling things, my opinion is you should just let installapplications download it for you, or make a package.

But if you must, please silent it's output.

**Comment by MichalMMac** [comment]
Yes I fixed it using `--silent` switch which I should used from the start.  However if `curl` stderr output can crash installapplications something else migt too. That's why I repoted this.

(I am no curling things to downloaded them. I am calling API serverside to do something for me (sync Munki manifest state with Airwatch state. Basically update device manifest to include others manifests.))

**Comment by erikng** [comment]
I'm happy to accept a pull request that resolves this issue but I don't plan on working on it myself. Any APIs I interact with I use python and don't run into issues like this.

The main issue is curl is passing text that NSLog doesn't like. One way to potentially get around this is to pass a try to NSLog and then continue if it can't pass this. This should theoretically still print the error to the actual log file and fix the crash. 

If you want to test that theory and confirm, I can merge it. I just don't have the time to create a shell script that interacts with an API through curl to debug this.

**Comment by erikng** [comment]
For context, this issue was happening for other things (like you suggested) and I fixed those bugs long ago. Curl seems to be the only tool people reliably hit issues with over the past year+.

**Comment by MichalMMac** [comment]
Ok. Thanks for intput I might look into.

We could leave this issue here anyway if others encounter this situation.

**Comment by erikng** [comment]
Perhaps send me a PR for the README to point this out? or add to the wiki

**Comment by MichalMMac** [comment]
I see ihis has been already mentioned in the wiki https://github.com/erikng/installapplications/wiki/Troubleshooting

**Comment by sheagcraig** [comment]
Springing back to life!

I have seen this on occasion also. In my experience, it hasn't been curl, but possibly Munki. And specifically, my script is running Munki and just letting it output to stdout and stderr rather than capturing it (i.e. `subprocess.check_call`). I haven't figured out what it's so upset about specifically, but my solution is going to be to just grab those output streams so they don't get caught by `installapplications.runrootscript` which then tries to format them in.

That being said, I'd be happy to provide a PR that adds an exception handler for this just to prevent it from happening in the future, if you'd be so inclined (@erikng )
