### ISSUE TITLE
userland rootscript does not wait for userland

### ISSUE THREAD

**Issue by MichalMMac** [erikng/installapplications#48]
Currently [code](https://github.com/erikng/installapplications/blob/699e3ab550193892216bb0bc247a6211515f1d31/payload/Library/Application%20Support/installapplications/installapplications.py#L641) for checking if we are not in setupassistant is only in package installation if/else branch.

When there is no package in userland section of `installapplications.json` (only rootscripts), `installapplications.py` does not wait for user to log in. Rootscripts in userland section  are executed during setup assistant as if they were in setupassistant section.

Is there a reason for this or should we improve the code?

I created PR #49 with simple change to deal with this. (I did not study entire `installapplications.py` source code).

**Comment by erikng** [comment]
Definitely a bug.

Thanks,
Erik Gomez
________________________________

**Comment by erikng** [comment]
Now addressed in new version
