### ISSUE TITLE
Feature request: ability to have a custom-named bootstrap.json

### ISSUE THREAD

**Issue by flammable** [erikng/installapplications#53]
Hey Erik -

Would it be possible to support bootstrap files that aren't named `bootstrap.json`? I'm looking to introduce multiple bootstrap pkgs in my environment, but as they'd share scripts/pkgs, I'd like to have multiple bootstrap.json files in the root directory of my IAs file share.

At the moment, I see the name `bootstrap.json` is hardcoded in `installapplications.py` (line 432) and `generatejson.py` (line 230). Even if I change `/Library/LaunchDaemons/com.erikng.installapplications.plist` to point to `bootstrap_foo.json`, it looks like I'll need to hardcode the new name in the other two scripts.

No worries if it's not something you'd like to support - just figured I'd ask before making those changes myself.

Thanks!

Mike

**Comment by erikng** [comment]
the URL can be anything you want it to be in your launch agent, it's just `bootstrap.json` is hard coded as the saved path on the client device.

We have about six different jsons on our webserver, all on the same root location.
