### ISSUE TITLE
Cleanup removes embedded Python before reboot command is issued

### ISSUE THREAD

**Issue by lucasjhall** [erikng/installapplications#58]
## context

- IA is running a bash root script in userland
- Using `master` and embedded python 
- reboot command is issued and present in IA log w/o errors
- `[InstallApplications] Triggering reboot`

## workaround

- issuing the same command via bash in the subprocess call works as expected 
- `/sbin/shutdown -r now` 
- have IA check for a installed item/sha and then `exit 0` after restart
- not ideal, hence workaround 

## further investigation 

- moved `installapplications` to `Library` 
- ran test.py to simply test the python reboot call

```python
#!/Library/installapplications/Python.framework/Versions/3.8/bin/python3
...
subprocess.call(['/sbin/shutdown', '-r', 'now'])
...
```
- that worked as expected 

## hypothesis

- `cleanup(0)` being triggered prior to a reboot breaks embedded python

```python
    cleanup(0)

    if reboot:
        iaslog('Triggering reboot')
        subprocess.call(['/sbin/shutdown', '-r', 'now'])
```

- so calling the embedded python at `/Library/installapplications/Python.framework/Versions/3.8/bin/python3` would fail
- it doesn't exist, since we just cleaned it up 
- but this script is still in memory so it works?

**Comment by lucasjhall** [comment]
@erikng 

I pulled [fixrebootpy3](erikng/installapplications/tree/fixrebootpy3) and deployed. 

The process ended in a reboot as expected.

**Comment by erikng** [comment]
Did everything cleanup?

Was the last log event after the reboot a cleanup entry?

**Comment by lucasjhall** [comment]
Yes, verified:
- `/Libraryinstallpllications/*` was removed
- LaunchAgent and LaunchDaemon were removed.  

Logs appeared as expected:
```text
...
Python[107:1419] [InstallApplications] Starting root script: /Library/installapplications/script.sh
Python[107:1419] [InstallApplications] Running Script: /Library/installapplications/script.sh
Python[107:1419] [InstallApplications] Attempting to remove LaunchDaemon: /Library/LaunchDaemons/com.erikng.installapplications.plist
Python[107:1419] [InstallApplications] Attempting to remove LaunchAgent: /Library/LaunchAgents/com.erikng.installapplications.plist
Python[107:1419] [InstallApplications] Targeting user id for LaunchAgent removal: 0
Python[107:1419] [InstallApplications] Attempting to remove LaunchAgent: com.erikng.installapplications
Python[107:1419] [InstallApplications] Attempting to remove InstallApplications directory: /Library/installapplications
Python[107:1419] [InstallApplications] Attempting to remove LaunchDaemon: com.erikng.installapplications
Python[107:1419] [InstallApplications] Cleanup done. Exiting.
```

**Comment by erikng** [comment]
Hm, could have sworn on the branch there should have been a reboot log event prior to the last message.

**Comment by erikng** [comment]
Addressed with https://github.com/erikng/installapplications/pull/59
